# Generated by Django 5.0.7 on 2024-07-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='uploadFile',
            field=models.FileField(blank=True, null=True, upload_to='upload_to', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='object',
            name='sharedLink',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Shared Link'),
        ),
    ]
